### ISSUE TITLE
$input crashes command

### ISSUE THREAD

**Issue by stjernegard** [ericpridham/sublime-commando#4]
Whenever I use `$input` in a command, it crashes.

``` json
[
  {
    "caption": "Git: Checkout Branch",
    "command": "commando",
    "args": {
      "commands": [
       ["commando_input_panel", {
          "caption": "Branch name: ",
          "initial_text": "master",
          "on_done": [
            ["commando_exec", {"cmd": ["git", "checkout", "$input"]}]
          ]
        }]
      ]
    }
  }
]
```

I would expect this command to check out a new branch. Instead it fails:

```
Exception in thread Thread-12:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "commands in /Users/dannistjernegard/Library/Application Support/Sublime Text 3/Installed Packages/Commando.sublime-package", line 274, in run
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1386, in _execute_child
TypeError: Can't convert 'NoneType' object to str implicitly

Traceback (most recent call last):
  File "commands in /Users/dannistjernegard/Library/Application Support/Sublime Text 3/Installed Packages/Commando.sublime-package", line 86, in watch_proc
  File "commands in /Users/dannistjernegard/Library/Application Support/Sublime Text 3/Installed Packages/Commando.sublime-package", line 308, in poll
AttributeError: 'NoneType' object has no attribute 'poll'
```

**Comment by ericpridham** [comment]
@stjernegard I can only seem to reproduce this error if I explicitly translate "$input" to None, so I'm curious about the exact commands.  Can you open up the console and enter `sublime.log_commands(True)` then re-run the command above and paste to me the relevant command log?

**Comment by stjernegard** [comment]
@ericpridham 

The relevant part of the log:

```
command: show_overlay {"overlay": "command_palette"}
command: commando {"commands": [["commando_input_panel", {"caption": "Branch name: ", "initial_text": "master", "on_done": [["commando_exec", {"cmd": ["git", "checkout", "$input"]}]]}]]}
command: commando_input_panel {"context": {"args": {"caption": "Branch name: ", "initial_text": "master", "on_done": [["commando_exec", {"cmd": ["git", "checkout", "$input"]}]]}, "commands": [], "input": null, "view_id": 20, "window_id": 2}}
command: commando_exec {"context": {"args": {"cmd": ["git", "checkout", "$input"]}, "commands": [], "input": null, "view_id": 20, "window_id": 2}}
Exception in thread Thread-13:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "commands in /Users/dannistjernegard/Library/Application Support/Sublime Text 3/Installed Packages/Commando.sublime-package", line 274, in run
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1386, in _execute_child
TypeError: Can't convert 'NoneType' object to str implicitly

Traceback (most recent call last):
  File "commands in /Users/dannistjernegard/Library/Application Support/Sublime Text 3/Installed Packages/Commando.sublime-package", line 86, in watch_proc
  File "commands in /Users/dannistjernegard/Library/Application Support/Sublime Text 3/Installed Packages/Commando.sublime-package", line 308, in poll
AttributeError: 'NoneType' object has no attribute 'poll'
```

**Comment by ericpridham** [comment]
@stjernegard Excellent, thanks for that. Looks like I had this fixed in master but never did a release for it. I just did a 0.2.2 release which should hit package control shortly.

**Comment by ericpridham** [comment]
@stjernegard Hey, I'm just wondering if release 0.2.2 fixed your issue.

**Comment by stjernegard** [comment]
Yea, it works now, thanks :+1:
